
---
- hosts: ec2
  become: true
  tasks:
    - name: Stop service docker, if started
      ansible.builtin.service:
        name: docker
        state: stopped
    - name: Disable service docker
      ansible.builtin.service:
        name: docker
        enabled: no
    - name: Install httpd
      yum:
        name: httpd
        state: present
        update_cache: yes
    - name: Start httpd
      ansible.builtin.service:
        name: httpd
        state: started
    - name: Enable httpd
      ansible.builtin.service:
        name: httpd
        enabled: yes
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /home/sinensia/hello-2048/public_html/
        dest: /var/www/html/
        owner: apache
        group: apache
        mode: '0644'
        directory_mode: '0755'
